### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by jvhoven** [42BV/mad-react-url#14]
Most of the examples in the documentation still use `RouteComponentProps` instead of the preferred `useLocation`, `useHistory` hooks.

Additionally add a link to the GitHub repository:

`_config.yml`
```
links:
  - name: 'View on Github'
    icon: 'https://unpkg.com/simple-icons@latest/icons/github.svg'
    href: 'https://github.com/42BV/jarb-final-form'
```
